In [3]:
import pandas as pd

In [4]:
data = [['Harry', 34], ["Jack", 30], ["Rohan", 16], ["Shubh", 20]]

In [5]:
data

[['Harry', 34], ['Jack', 30], ['Rohan', 16], ['Shubh', 20]]

In [6]:
pd.DataFrame(data)

       0   1
0  Harry  34
1   Jack  30
2  Rohan  16
3  Shubh  20

In [7]:
pd.DataFrame(data, columns=['Name', 'Age'])

    Name  Age
0  Harry   34
1   Jack   30
2  Rohan   16
3  Shubh   20

In [8]:
data = {'a': [1, 2, 3, 4], 'b': [5, 6, 7, 8]}

In [9]:
data

{'a': [1, 2, 3, 4], 'b': [5, 6, 7, 8]}

In [10]:
df = pd.DataFrame(data)

In [11]:
df

   a  b
0  1  5
1  2  6
2  3  7
3  4  8

In [12]:
pd.read_excel("data.xlsx")

     Name     School  Marks
0  Shubham       olx     34
1     Jack       bba     43
2     Alex       wps     24
3     Hary       aps     87
4   Bhadva  mcSchool     75
5   Akash         bc     98
6  Jasmine  mzSchool     12

In [13]:
df = pd.read_excel("data.xlsx")

In [14]:
df

     Name     School  Marks
0  Shubham       olx     34
1     Jack       bba     43
2     Alex       wps     24
3     Hary       aps     87
4   Bhadva  mcSchool     75
5   Akash         bc     98
6  Jasmine  mzSchool     12

In [16]:
df = pd.read_json("data.json")

In [17]:
df

     name  age      city
0  Shreya   25  New York
1    Jack   35  Old York

In [ ]:
df = pd.read_csv("https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv")

ParserError: Error tokenizing data. C error: Expected 1 fields in line 39, saw 2