In [3]:
import pandas as pd

In [4]:
data = [['harry', 34], ['jack', 67], ['jaccob', 67], ['shubham', 67]]

In [5]:
pd.DataFrame(data,columns=['Name', 'Age'])

      Name  Age
0    harry   34
1     jack   67
2   jaccob   67
3  shubham   67

In [6]:
df = pd.DataFrame(data)

In [7]:
df

         0   1
0    harry  34
1     jack  67
2   jaccob  67
3  shubham  67