In [20]:
import pandas as pd

In [21]:
data = [['harry', 34], ['jack', 67], ['jaccob', 67], ['shubham', 67]]

In [22]:
pd.DataFrame(data,columns=['Name', 'Age'])

      Name  Age
0    harry   34
1     jack   67
2   jaccob   67
3  shubham   67

In [23]:
df = pd.DataFrame(data)

In [24]:
df

         0   1
0    harry  34
1     jack  67
2   jaccob  67
3  shubham  67

In [25]:
df = pd.read_excel("data.xlsx")

ImportError: `Import openpyxl` failed.  Use pip or conda to install the openpyxl package.