In [1]:
import pandas as pd

In [2]:
data = [['Harry', 34], ["Jack", 30], ["Rohan", 16], ["Shubh", 20]]

In [3]:
data

[['Harry', 34], ['Jack', 30], ['Rohan', 16], ['Shubh', 20]]

In [4]:
pd.DataFrame(data)

       0   1
0  Harry  34
1   Jack  30
2  Rohan  16
3  Shubh  20

In [5]:
pd.DataFrame(data, columns=['Name', 'Age'])

    Name  Age
0  Harry   34
1   Jack   30
2  Rohan   16
3  Shubh   20

In [6]:
data = {'a': [1, 2, 3, 4], 'b': [5, 6, 7, 8]}

In [7]:
data

{'a': [1, 2, 3, 4], 'b': [5, 6, 7, 8]}

In [8]:
df = pd.DataFrame(data)

In [9]:
df

   a  b
0  1  5
1  2  6
2  3  7
3  4  8

In [10]:
import numpy as np

In [11]:
arr = np.array([[1,2], [3,4], [5,6]])

In [12]:
df = pd.DataFrame(arr, columns=["A", "B"])

In [13]:
df

   A  B
0  1  2
1  3  4
2  5  6