In [1]:
import pandas as pd

In [2]:
data = [['Harry', 34], ["Jack", 30], ["Rohan", 16], ["Shubh", 20]]

In [3]:
data

[['Harry', 34], ['Jack', 30], ['Rohan', 16], ['Shubh', 20]]

In [4]:
pd.DataFrame(data)

       0   1
0  Harry  34
1   Jack  30
2  Rohan  16
3  Shubh  20

In [5]:
pd.DataFrame(data, columns=['Name', 'Age'])

    Name  Age
0  Harry   34
1   Jack   30
2  Rohan   16
3  Shubh   20

In [ ]:
data = {'a': [1, 2, 3, 4], 'b': [5, 6, 7, 8]}